Repository zalando-incubator/kopf, pull requests merged in 2019-04, with the labels that each got.

#22 Pass the field diff to the field handlers, not the obj diff
  kopf/reactor/handling.py
  kopf/structs/diffs.py
Labels: bug

#26 Enable asyncio tests & mocks
  requirements.txt
  tests/conftest.py
  tests/test_async.py
Labels: enhancement

#27 Replace built-in StopIteration with custom StopStreaming for API calls
  kopf/reactor/queueing.py
  kopf/reactor/watching.py
  tests/test_streaming.py
Labels: bug

#14 Initial documentation
  .gitignore
  README.md
  docs/alternatives.rst
  docs/async.rst
  docs/cleanup.rst
  docs/concepts.rst
  docs/conf.py
  docs/deployment-depl.yaml
  docs/deployment-rbac.yaml
  docs/deployment.rst
  docs/errors.rst
  docs/events.rst
  docs/handlers.rst
  docs/hierarchies.rst
  docs/index.rst
  docs/install.rst
  docs/loading.rst
  docs/minikube.rst
  docs/naming.rst
  docs/peering.rst
  docs/requirements.txt
  docs/scopes.rst
  docs/vision.rst
  docs/walkthrough/creation.rst
  docs/walkthrough/deletion.rst
  docs/walkthrough/diffs.rst
  docs/walkthrough/prerequisites.rst
  docs/walkthrough/problem.rst
  docs/walkthrough/resources.rst
  docs/walkthrough/starting.rst
  docs/walkthrough/updates.rst
  kopf/on.py
  kopf/reactor/handling.py
  kopf/reactor/lifecycles.py
  kopf/reactor/peering.py
  kopf/reactor/queueing.py
  kopf/structs/diffs.py
  kopf/structs/lastseen.py
  kopf/structs/progress.py
Labels: documentation

#38 [GH-33] implement auto detection mode for peering.
  docs/peering.rst
  kopf/cli.py
  kopf/reactor/peering.py
  kopf/reactor/queueing.py
Labels: enhancement

#41 Adapt the README for PyPI
  LICENSE
  README.md
  setup.py
Labels: documentation

#43 Handle only the latest event with the most up to date state
  kopf/reactor/queueing.py
Labels: bug

#50 Fix the docs for the RBAC examples, and add "get" permission on peering
  docs/deployment-rbac.yaml
  docs/deployment.rst
Labels: bug, documentation

#34 Test the callback invocation protocol
  kopf/reactor/handling.py
  kopf/reactor/invocation.py
  tests/invocations/test_callbacks.py
Labels: automation

#28 Tests for object hierarchies
  kopf/__init__.py
  kopf/structs/hierarchies.py
  tests/hierarchies/conftest.py
  tests/hierarchies/test_labelling.py
  tests/hierarchies/test_name_harmonizing.py
  tests/hierarchies/test_namespace_adjusting.py
  tests/hierarchies/test_owner_referencing.py
Labels: automation

#39 Test the CLI invocation, including logging in & preloading
  kopf/cli.py
  kopf/config.py
  tests/cli/conftest.py
  tests/cli/test_help.py
  tests/cli/test_logging.py
  tests/cli/test_login.py
  tests/cli/test_options.py
  tests/cli/test_preloading.py
Labels: automation
