Repository zalando-incubator/kopf, pull requests merged in 2019-06, with the labels that each got.

#86 Add the silent spy-handlers for the raw events, no persistence
  docs/handlers.rst
  examples/08-events/README.md
  examples/08-events/example.py
  kopf/on.py
  kopf/reactor/handling.py
  kopf/reactor/invocation.py
  kopf/reactor/registries.py
  kopf/structs/status.py
  tests/cli/test_preloading.py
  tests/handling/conftest.py
  tests/handling/test_cause_handling.py
  tests/handling/test_event_handling.py
  tests/registries/test_decorators.py
  tests/registries/test_global_registry.py
  tests/registries/test_handler_matching.py
  tests/registries/test_id_detection.py
  tests/registries/test_registering.py
  tests/test_progress.py
Labels: enhancement

#83 Document the operator maintenance
  docs/continuity.rst
  docs/idempotence.rst
  docs/index.rst
  docs/troubleshooting.rst
Labels: documentation

#90 Test for finalizers
  kopf/structs/finalizers.py
  tests/test_finalizers.py
Labels: automation

#89 Add the new-style events (of v1 core API) to the RBAC docs
  docs/deployment-rbac.yaml
Labels: documentation

#103 Skip handling & logging when there are no handlers
  kopf/reactor/causation.py
  kopf/reactor/handling.py
  tests/e2e/test_examples.py
  tests/handling/test_cause_handling.py
  tests/handling/test_delays.py
  tests/handling/test_errors.py
  tests/handling/test_event_handling.py
  tests/handling/test_multistep.py
  tests/handling/test_no_handlers.py
  tests/handling/test_timeouts.py
Labels: enhancement

#91 Tests for last-seen state calculation and comparison
  kopf/structs/lastseen.py
  kopf/test_lastseen.py
Labels: automation

#102 Feature/patches 0xflotus
  docs/contributing.rst
  docs/hierarchies.rst
  docs/loading.rst
Labels: documentation

#104 Log diffs when present
  kopf/reactor/handling.py
  tests/handling/conftest.py
  tests/handling/test_cause_handling.py
  tests/handling/test_cause_logging.py
Labels: enhancement

#108 Label sub-templates recursively
  kopf/reactor/handling.py
  kopf/structs/dicts.py
  kopf/structs/diffs.py
  kopf/structs/hierarchies.py
  tests/diffs-n-dicts/test_diff.py
  tests/diffs-n-dicts/test_parsing.py
  tests/diffs-n-dicts/test_reduction.py
  tests/diffs-n-dicts/test_resolving.py
  tests/diffs-n-dicts/test_walking.py
  tests/hierarchies/test_labelling.py
  tests/hierarchies/test_owner_referencing.py
Labels: automation, enhancement

#105 Add "resuming" handlers for resources (as co-handlers)
  docs/handlers.rst
  kopf/k8s/watching.py
  kopf/on.py
  kopf/reactor/causation.py
  kopf/reactor/registries.py
  tests/basic-structs/test_cause.py
  tests/basic-structs/test_handler.py
  tests/handling/conftest.py
  tests/handling/test_delays.py
  tests/handling/test_errors.py
  tests/handling/test_multistep.py
  tests/handling/test_timeouts.py
  tests/reactor/conftest.py
  tests/reactor/test_queueing.py
  tests/registries/test_handler_matching.py
Labels: enhancement

#95 RBAC for automatic legacy peering detection
  docs/deployment-rbac.yaml
  kopf/k8s/fetching.py
  tests/k8s/test_list_objs.py
  tests/k8s/test_make_list_fn.py
  tests/k8s/test_read_crd.py
  tests/k8s/test_read_obj.py
Labels: automation, documentation
