Repository zalando-incubator/kopf, pull requests merged in 2019-12, with the labels that each got.

#265 Ensure predictable mypy's type-checking rules in CI/CD
  requirements.txt
Labels: automation

#270 [269] Fix broken CI/CD tests due to Minikube w/ K8s 1.17.0 + RBAC
  tools/minikube-for-travis.sh
Labels: automation, bug

#262 Fix bug #261, JSONPath should include the function name
  examples/crd.yaml
Labels: documentation

#274 [272] Enforce the version of `coverage` manually (pip fails to resolve)
  requirements.txt
Labels: automation

#276 [275] Parse JSON lines ourselves to avoid aiohttp's "Line is too long"
  kopf/clients/watching.py
  tests/k8s/test_watching.py
  tests/k8s/test_watching_iterjsonlines.py
Labels: bug

#257 Reset watch-streams for the freeze mode, relist on unfreezing
  kopf/clients/watching.py
  kopf/reactor/handling.py
  kopf/reactor/queueing.py
  kopf/reactor/running.py
  tests/handling/test_cause_handling.py
  tests/handling/test_cause_logging.py
  tests/handling/test_delays.py
  tests/handling/test_errors.py
  tests/handling/test_event_handling.py
  tests/handling/test_freezing.py
  tests/handling/test_multistep.py
  tests/handling/test_no_handlers.py
  tests/handling/test_retrying_limits.py
  tests/k8s/test_watching.py
Labels: enhancement
