Repository zalando-incubator/kopf, pull requests merged in 2020-01, with the labels that each got.

#278 Improve the GitHub issues/prs templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTORS.md
  SECURITY.md
Labels: automation

#285 Distinguish "no handlers at all" and "no handers for now" cases
  kopf/reactor/handling.py
  kopf/reactor/states.py
  tests/handling/test_timing_consistency.py
Labels: bug

#277 [246] Prepare for aiohttp v4, but stay with v3
  kopf/clients/auth.py
  kopf/clients/discovery.py
  kopf/clients/events.py
  kopf/clients/fetching.py
  kopf/clients/patching.py
  kopf/clients/watching.py
  setup.py
  tests/authentication/test_credentials.py
  tests/authentication/test_reauthentication.py
  tests/authentication/test_tempfiles.py
  tests/conftest.py
Labels: bug

#288 Remove Reason.ACQUIRE and Reason.RELEASE
  kopf/reactor/causation.py
  kopf/reactor/handling.py
  tests/causation/test_detection.py
  tests/handling/conftest.py
  tests/handling/test_cause_handling.py
  tests/handling/test_no_handlers.py
Labels: refactoring

#258 Filter by arbitrary callback function
  docs/handlers.rst
  examples/11-filtering-handlers/example.py
  examples/11-filtering-handlers/test_example_11.py
  kopf/on.py
  kopf/reactor/handling.py
  kopf/reactor/invocation.py
  kopf/reactor/registries.py
  kopf/toolkits/legacy_registries.py
  tests/registries/legacy/test_legacy_decorators.py
  tests/registries/legacy/test_legacy_requires_finalizer.py
  tests/registries/test_decorators.py
  tests/registries/test_handler_matching.py
  tests/registries/test_requires_finalizer.py
Labels: enhancement

#298 Rebalance the modules to reduce complexity
  kopf/__init__.py
  kopf/engines/peering.py
  kopf/engines/probing.py
  kopf/on.py
  kopf/reactor/activities.py
  kopf/reactor/callbacks.py
  kopf/reactor/errors.py
  kopf/reactor/handlers.py
  kopf/reactor/handling.py
  kopf/reactor/invocation.py
  kopf/reactor/lifecycles.py
  kopf/reactor/processing.py
  kopf/reactor/queueing.py
  kopf/reactor/registries.py
  kopf/reactor/running.py
  kopf/reactor/states.py
  kopf/toolkits/legacy_registries.py
  tests/basic-structs/test_handlers.py
  tests/basic-structs/test_handlers_deprecated_cooldown.py
  tests/handling/test_activity_triggering.py
  tests/handling/test_cause_handling.py
  tests/handling/test_cause_logging.py
  tests/handling/test_delays.py
  tests/handling/test_errors.py
  tests/handling/test_event_handling.py
  tests/handling/test_multistep.py
  tests/handling/test_no_handlers.py
  tests/handling/test_retrying_limits.py
  tests/handling/test_timing_consistency.py
  tests/persistence/test_outcomes.py
  tests/reactor/conftest.py
  tests/reactor/test_queueing.py
  tests/registries/test_decorators.py
Labels: refactoring

#302 Enable LGTM checks and fix few LGTM alerts
  README.md
  examples/04-events/example.py
  examples/13-hooks/example.py
  kopf/clients/auth.py
  kopf/on.py
  kopf/reactor/running.py
Labels: refactoring

#97 Update the EphemeralVolumeClaim story-telling
  docs/walkthrough/creation.rst
  docs/walkthrough/deletion.rst
  docs/walkthrough/diffs.rst
  docs/walkthrough/prerequisites.rst
  docs/walkthrough/problem.rst
  docs/walkthrough/resources.rst
  docs/walkthrough/starting.rst
  docs/walkthrough/updates.rst
Labels: documentation
